### PR TITLE
fix english/german translation - fixes #19

### LINKED ISSUE #19: Check and fix english/german translation
Some things are missing in english -> e.g.:
tablauncher_und_resmio_api_ _wordpress

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

File: index.php [hunk 1]
```diff
@@ -2,9 +2,46 @@
 transitional.dtd">
 <html xmlns="http://www.w3.org/1999/xhtml" lang="de">
 <head profile="http://gmpg.org/xfn/11">
-  
-  
+ 
+<link rel="stylesheet" type="text/css" href="<?php bloginfo('stylesheet_directory'); ?>/resmio-api/css/resmio-style.css">
```
Comment (PSahner) [inline index.php]: @RNDWSR 
Auszug von https://developer.wordpress.org/reference/functions/bloginfo/
bloginfo_____function___wordpress_developer_resources

-> Bitte entsprechend abändern (line 6 + 15)

**Comment by PSahner** [comment]
@RNDWSR see line note under files changed

File: languages/en_US.po [hunk 2]
```diff
@@ -22,46 +22,71 @@ msgstr ""
...
 
+#: index.php:26 /resmio-api/resmio-api.php:424
 msgid "E-Mail"
 msgstr "Email"
 
-msgid "Einstellungen für resmio API"
-msgstr "Settings for resmio API"
+#: index.php:27 /resmio-api/resmio-api.php:439
+msgid "soziale Plattformen"
+msgstr "Social Platforms"
```
Comment (PSahner) [inline languages/en_US.po]: @RNDWSR in english I think it's better to call them "social network(s)" and only small caps
